-- AlterEnum: add BLOCKED to SlotType
ALTER TABLE `availability_slots` MODIFY COLUMN `slot_type` ENUM('INDIVIDUAL', 'GROUP', 'BLOCKED') NOT NULL DEFAULT 'INDIVIDUAL';
ALTER TABLE `recurring_patterns` MODIFY COLUMN `slot_type` ENUM('INDIVIDUAL', 'GROUP', 'BLOCKED') NOT NULL DEFAULT 'INDIVIDUAL';
