/**
 * RecurringPreview — shows which dates will be generated by a recurring pattern
 * and flags conflicts with existing slots.
 *
 * CAL-006: Recurring availability previews generated and skipped conflicts.
 *
 * This is a pure presentational component — it derives dates client-side
 * from the form state and highlights any day where a slot already exists
 * at the same time. The professor can proceed anyway (backend handles conflicts)
 * or adjust days/times.
 */
import { useTranslation } from 'react-i18next';
import { format, addWeeks, getDay } from 'date-fns';
import { AlertCircle, CalendarCheck2, CalendarX2 } from 'lucide-react';
import { cn } from '@/lib/utils';
import type { AvailabilitySlot } from '@spanish-class/shared';

export interface RecurringPreviewProps {
  /** Selected days of week (0 = Sun, 1 = Mon, … 6 = Sat) */
  daysOfWeek: number[];
  /** Start date for the recurring series */
  startDate: Date | null;
  /** How many weeks ahead to generate */
  weeksAhead: number;
  /** Start time in "HH:MM" format */
  startTime: string;
  /** End time in "HH:MM" format */
  endTime: string;
  /** Existing slots to check for conflicts */
  existingSlots: AvailabilitySlot[];
  className?: string;
}

/** Returns all generated Date objects for the recurring pattern. */
function generateDates(
  daysOfWeek: number[],
  startDate: Date,
  weeksAhead: number,
): Date[] {
  const dates: Date[] = [];
  for (let w = 0; w < weeksAhead; w++) {
    const weekBase = addWeeks(startDate, w);
    // Find the Monday of this week
    const dayOfWeek = getDay(weekBase); // 0 = Sun
    const mondayOffset = dayOfWeek === 0 ? -6 : 1 - dayOfWeek;
    const monday = new Date(weekBase);
    monday.setDate(monday.getDate() + mondayOffset);

    daysOfWeek.forEach((d) => {
      // d: 0=Sun,1=Mon... shift to match monday base
      const offset = d === 0 ? 6 : d - 1; // 0=Mon offset
      const date = new Date(monday);
      date.setDate(monday.getDate() + offset);
      if (date >= startDate) dates.push(date);
    });
  }
  return dates.sort((a, b) => a.getTime() - b.getTime());
}

/** Returns true if an existing slot overlaps with the given date + time range. */
function hasConflict(
  date: Date,
  startTime: string,
  endTime: string,
  slots: AvailabilitySlot[],
): boolean {
  const [sh, sm] = startTime.split(':').map(Number);
  const [eh, em] = endTime.split(':').map(Number);
  const newStart = new Date(date);
  newStart.setHours(sh, sm, 0, 0);
  const newEnd = new Date(date);
  newEnd.setHours(eh, em, 0, 0);

  return slots.some((slot) => {
    const slotStart = new Date(slot.startTime);
    const slotEnd   = new Date(slot.endTime);
    // Overlap: newStart < slotEnd && newEnd > slotStart
    return (
      format(slotStart, 'yyyy-MM-dd') === format(date, 'yyyy-MM-dd') &&
      newStart < slotEnd &&
      newEnd > slotStart
    );
  });
}

export function RecurringPreview({
  daysOfWeek,
  startDate,
  weeksAhead,
  startTime,
  endTime,
  existingSlots,
  className,
}: RecurringPreviewProps) {
  const { t } = useTranslation('admin');

  if (!startDate || daysOfWeek.length === 0) return null;

  const dates = generateDates(daysOfWeek, startDate, weeksAhead);
  const conflicts = dates.filter((d) => hasConflict(d, startTime, endTime, existingSlots));
  const cleanDates = dates.filter((d) => !hasConflict(d, startTime, endTime, existingSlots));

  // Only show the first 12 clean dates to keep the UI compact
  const preview = cleanDates.slice(0, 12);
  const hiddenCount = cleanDates.length - preview.length;

  return (
    <div className={cn('space-y-3', className)}>
      <div className="flex items-center justify-between">
        <p className="text-small font-semibold text-ink">
          {t('calendar.recurring_preview_title')}
        </p>
        <span className="text-caption text-ink-tertiary">
          {t('calendar.recurring_generating', { count: cleanDates.length })}
        </span>
      </div>

      {/* Conflict warning */}
      {conflicts.length > 0 && (
        <div className="flex items-start gap-2 px-3 py-2 rounded-ui-sm bg-alert-warning-surface border border-alert-warning-border text-alert-warning-foreground text-caption">
          <AlertCircle className="h-3.5 w-3.5 mt-0.5 shrink-0" aria-hidden="true" />
          <span>
            {t('calendar.recurring_conflicts', { count: conflicts.length })}
          </span>
        </div>
      )}

      {/* Preview grid — first 12 clean dates */}
      <div className="grid grid-cols-2 gap-1.5 sm:grid-cols-3">
        {preview.map((date) => (
          <div
            key={date.toISOString()}
            className="flex items-center gap-2 px-2.5 py-1.5 rounded-ui-xs bg-surface-raised border border-line"
          >
            <CalendarCheck2 className="h-3.5 w-3.5 text-status-available-foreground shrink-0" aria-hidden="true" />
            <div className="min-w-0">
              <p className="text-caption font-semibold text-ink truncate">{format(date, 'EEE, MMM d')}</p>
              <p className="text-micro text-ink-tertiary">{startTime} – {endTime}</p>
            </div>
          </div>
        ))}
        {conflicts.map((date) => (
          <div
            key={date.toISOString()}
            className="flex items-center gap-2 px-2.5 py-1.5 rounded-ui-xs bg-alert-warning-surface border border-alert-warning-border opacity-70"
          >
            <CalendarX2 className="h-3.5 w-3.5 text-alert-warning-foreground shrink-0" aria-hidden="true" />
            <div className="min-w-0">
              <p className="text-caption font-semibold text-ink truncate">{format(date, 'EEE, MMM d')}</p>
              <p className="text-micro text-alert-warning-foreground">{t('calendar.recurring_conflict_skip')}</p>
            </div>
          </div>
        ))}
      </div>

      {/* Hidden count */}
      {hiddenCount > 0 && (
        <p className="text-caption text-ink-tertiary text-center">
          +{hiddenCount} {t('calendar.recurring_more')}
        </p>
      )}
    </div>
  );
}
